### ISSUE TITLE
Feature request: error threshold before notifying

### ISSUE THREAD

**Issue by mmcgrath** [fnando/uptime_checker#2]
It would be excellent to have a way to say "only trigger the alerts (basecamp, slack etc.) when the error condition arises for the _n_ th time."

We get a lot of "blips" on some systems that individually, and in isolation, don't constitute an actionable downtime situation.  However, we might want to say, "if it is down for 3 consecutive checks then consider this the error condition and notify it."

**Comment by fnando** [comment]
You can now have this by defining `min_failures` on each check. The following example will notify only after 3 failing checks.

```yaml
checks:
  - name: My Site
    url: http://example.com
    notify: *notify
    status: 200
    min_failures: 3
```
