### ISSUE TITLE
Feature request: define different notifiers for each checker

### ISSUE THREAD

**Issue by muratso** [fnando/uptime_checker#4]
It would be nice to configure individually the notifier for each checker.

We have different projects with different Project Managers. It would be nice notify each one of them only for the application which they are responsible.

On the checkers we could have something like:

```
notify: &notify
  - stdout: ~
  - telegram: xxxxxx 
    #global notifier. It notifies whenever any of the application is offline

checkers:
  - name: Test App
    url: http://testapp.com.br/
    notify: *notify
    status: 200
    telegram: zzzzz 
    #specific notifier. It notifies only when this application is offline. 
    #But it also notifies to the global telegram notifier
    email: xpto@example.com (specific notifier)
```
